name: template
version: 0.0.0.0
maintainer: Boshen

ghc-options: -Wall
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
  - base >=4.12.0.0
  - foundation >= 0.0.23

library:
  source-dirs: lib
  exposed-modules:
    - Lib

executable:
  main: Main.hs
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  source-dirs:
    - src
    - lib

tests:
  spec:
    main: Spec.hs
    build-tools: hspec-discover
    source-dirs:
      - test
      - lib
    dependencies:
      - hspec
